name: LuckyVouchers
version: 1.0
api-version: 1.13
main: net.luckynetwork.luckyvouchers.LuckyVouchers
author: aglerr
depend: [LuckPerms]

commands:
  vouchers:
    aliases: [voucher, lv, luckyvouchers]